### ISSUE TITLE
Using function grid2nc() to download dataset

### ISSUE THREAD

**Issue by regi0008** [regi0008/S2Scalibrationextremeheat#6]
For example, the code for Climate Conserving Recalibration (CCR) method has errors returned: 

_Error in as.POSIXct.default(data$Dates$start, tz = "GMT", format = "%Y-%m-%d %H:%M:%S") : 
  do not know how to convert 'data$Dates$start' to class “POSIXct”_

**The current code is as shown below:**

#climate convering recalibration example
library(loadeR)
library(downscaleR)
library(transformeR)
library(visualizeR)
library(calibratoR)
library(loadeR.2nc)
library(ncdf4)
library(SpecsVerification)

#loading datasets of boreal winter temp over Iberia
#seasonal forecasts CFS
data(CFS_Iberia_tas)
fcst = CFS_Iberia_tas
#issue solved: need to constrain domain
fcst <- subsetGrid(CFS_Iberia_tas, lonLim = c(-10,10), latLim = c(30,45), years = 1983:2001)
#observational data NCEP
data(NCEP_Iberia_tas)
obs = NCEP_Iberia_tas

fcst <- aggregrateGrid(fcst, aggr.y = list(FUN = "mean", na.rm=TRUE))
obs <- aggregrateGrid(obs, aggr.y = list(FUN = "mean", na.rm = TRUE))

#interpolating forecasts to the observations' resolution
fcst <- interpGrid(fcst, new.coordinates = getGrid(obs))
#apply calibraton
fcst_cal <- calCCR(fcst, obs, crossval = TRUE, apply.to = "all")

#plot climo and call it calibrated_CCR
calibrated_CCR <- spatialPlot(makeMultiGrid(climatology(obs),
                                            climatology(fcst, by.member = FALSE), 
                                            climatology(fcst_cal, by.member = FALSE)),
                             backdrop.theme = "coastline",
                             layout = c(3, 1),
                             names.attr = c("NCEP", "CFS (raw)", "CFS (calibrated)"))

#print(calibrated_CCR)

str(calibrated_CCR)

#download / load as gridded data
#data(calibrated_CCR)
#name of output file
fileName <- "cal_CCR_gridded.nc"

#include a global attribute:
globalAttributeList <- list("institution" = "SantanderMetGroup, http://www.meteo.unican.es/")

#include two variable attribute:
varAttributeList <- list(var_attr1 = "one_attribute", var_attr2 = "another_attribute")

#create file
grid2nc(calibrated_CCR,
        NetCDFOutFile = fileName,
        missval = 1e20,
        prec = "float",
        globalAttributes = globalAttributeList,
        varAttributes = varAttributeList,
        shuffle = TRUE,
        verbose = TRUE)

Notes:
1) str(calibrated_CCR) would show a list of 45, but doesn't seem to return a data set.
2) Unsure if need the raster R-package to read the gridded spatial data.

**Comment by rykang11** [comment]
Deadline: Friday, 23 Aug 2019

**Comment by regi0008** [comment]
15/08/19:

Able to download as gridded dataset (as a ".nc" format) after advised edits, and able to plot out an image of "Temperature @ Specified height level above ground" via Panoply software plotting.

Both CCR and LM Panoply plots are similar, just a very small change in range of temperature.
