### ISSUE TITLE
Converting gridded data into .nc file for ROC Area plots

### ISSUE THREAD

**Issue by regi0008** [regi0008/S2Scalibrationextremeheat#8]
Issue with converting ROC Area gridded dataset to a .nc file.
Currently used for calibration method here is cal_CCR.

Code is as shown below:
#----------------------------------------------------------------------
library(loadeR)
library(downscaleR)
library(transformeR)
library(visualizeR)
library(calibratoR)
library(loadeR.2nc)
library(ncdf4)
library(abind)
library(s2dverification)
library(SpecsVerification)
library(easyVerification)
library(verification)
library(RColorBrewer)

writeNcdf <- function(gridData, filePath, missingValue = 1e20, tz = 'GMT', units = NULL, version = 3) {
  
  name <- gridData$Variable$varName
  # First defines dimensions.
  dimLon <- ncdim_def('lon', 'degrees_east', gridData$xyCoords$x)
  dimLat <- ncdim_def('lat', 'degrees_north', gridData$xyCoords$y)
  dimMem <- NULL
  if (!is.null(gridData$Members)) {
    dimMem <- ncdim_def('member', 'members', 0:(length(gridData$Members)-1))
  }
  
  # Time needs to be treated seperately
  dates <- as.POSIXlt(gridData$Dates$start, tz = tz)
  if (is.null(units)) {
    units <- getTimeUnit(dates)
    time <- difftime(dates, dates[1], units = units)
  } else {
    time <- difftime(dates, dates[1], units = units)
  }
  timeUnits <- paste(units, 'since', dates[1])
  # Here time needs to be numeric, as required by ncdf4 package, which is not the same
  # with ncdf
  dimTime <- ncdim_def('time', timeUnits, as.numeric(time))
  
  # Depending on whether there is a member part of the dataset.
  # default list
  dimList <- list(dimMem, dimTime, dimLat, dimLon)
  
  # In order to keep the dim list exactly the same with the original one, it needs to be changed.
  dimIndex <- grepAndMatch(c('member', 'time', 'lat', 'lon'), attributes(gridData$Data)$dimensions)
  dimIndex <- na.omit(dimIndex)
  
  # delete the NULL list, in order that there is no member part in the data.
  dimList <- Filter(Negate(is.null), dimList)
  # Then difines data
  var <- ncvar_def(name, "units", dimList, missingValue)
  
  # Here for ncdf4, there is an option to create version 4 ncdf, in future, it
  # may added here.
  if (version == 3) {
    nc <- nc_create(filePath, var) 
  } else if (version == 4) {
    nc <- nc_create(filePath, var, force_v4 = TRUE)
  } else {
    stop("Which ncdf version you want? Only 3 and 4 can be selected!")
  }
  
  if (!is.null(dimMem)){
    ncatt_put(nc, "member", "standard_name","realization")
    ncatt_put(nc, "member", "_CoordinateAxisType","Ensemble")
    ncatt_put(nc, "time", "standard_name","time")
    ncatt_put(nc, "time", "axis","T")
    ncatt_put(nc, "time", "_CoordinateAxisType","Time")
    #ncatt_put(nc, "time", "_ChunkSize",1)
    ncatt_put(nc, 'lat', "standard_name","latitude")
    ncatt_put(nc, 'lat', "_CoordinateAxisType","Lat")
    ncatt_put(nc, 'lon', "standard_name","longitude")
    ncatt_put(nc, 'lon', "_CoordinateAxisType","Lon")
  }
  
  # This part has to be put
  ncatt_put(nc, 0, "Conventions","CF-1.4")
  ncatt_put(nc, 0, 'WrittenBy', 'CCRS SSP Team, adapted from hyfo package')
  
  data <- aperm(gridData$Data, dimIndex)
  ncvar_put(nc, name, data)
  nc_close(nc)
  
}

# For internaluse by writeNcdf
getTimeUnit <- function(dates) {
  units <- c('weeks', 'days', 'hours', 'mins', 'secs')
  output <- NULL
  for (unit in units) {
    time <- difftime(dates, dates[1], units = unit)
    rem <- sapply(time, function(x) x%%1)
    if (!any(rem != 0)) {
      output <- unit
      break
    }
  } 
  return(output)
}

# in order to first grep than match.
# match only provides for exactly match, 
# dimIndex <- grepAndMatch(c('lon', 'lat', 'time', 'member'), dimNames)
grepAndMatch <- function(x, table) {
  index <- unlist(lapply(x, function(x) {
    a <- grep(x, table)
  }))
  return(index)
}
#------------------------------------------
#LOADING OF FILES THROUGH HYFO PACKAGE:
#need to make sure dimensions of both files are the same:
#calibrated hindcast: member, time, lat, lon
#obs_formatted: time, lat, lon
dir1 <- "C:/Users/regin/Desktop/R/S2Scalibrationextremeheat"
#predictor (calibrated hincast):
fcst_cal <- loadNcdf(file.path(dir1, "fcst_cal_CCR.nc"), "tas")

dir2 <- "C:/Users/regin/Desktop/R/S2Scalibrationextremeheat/loadeR"
#predictand (observation):
obs <- loadNcdf(file.path(dir2, "2t_era5_Mar_1993_2016_format.nc"), "tas")
#------------------------------------------
#VERIFICATION BETWEEN CALIBRATED HINDCAST AND OBSERVATIONS

#compute area under the ROC Curve via easyVerification package.
#EnsRoca computes the area under the ROC curve given the observations.
#tercile probabilities: let prob = 1:2/3.. or c(1/3,2/3)
#tdim = index of dimension with the different forecasts
#ensdim = index of dimension with the different ensemble members
roc <- veriApply(verifun = "EnsRoca",
                 fcst = fcst_cal$Data,
                 obs = obs$Data,
                 prob = 1:2/3)

#ERROR MESSAGE FROM THIS LINE BELOW:
#"Error in easyVeri2grid(easyVeri.mat = roc$cat3, obs.grid = obs, verifun = "EnsRoca") : 
#XY coordinates and matrix dimensions do not match"
#Dimension problem. To tackle above message, transpose roc$(whatever category)
#plot ROC AREA for each tercile category
#obs.grid = the grid containing the verifying reference used
#easyVeri2grid returns a climatological grid.
upper.tercile <- easyVeri2grid(easyVeri.mat = t(roc$cat3),
                               obs.grid = obs,
                               verifun = "EnsRoca")
str(upper.tercile)

#to plot ROCA diagram (for upper tercile)
spatialPlot(upper.tercile,
            backdrop.theme= "countries",
            main = "ROC AREA (Above-normal) for March",
            color.theme = "YlOrRd")

fcst_cal_fileName <- "calCCR_March_ROCA_AN.nc"
writeNcdf(upper.tercile, fcst_cal_fileName)

middle.tercile <- easyVeri2grid(easyVeri.mat = t(roc$cat2),
                                obs.grid = obs,
                                verifun = "EnsRoca")

#to plot ROCA diagram
spatialPlot(middle.tercile,
            backdrop.theme= "countries",
            main = "ROC AREA (Near-normal) for March",
            color.theme = "YlOrRd")

lower.tercile <- easyVeri2grid(easyVeri.mat = t(roc$cat1),
                               obs.grid = obs,
                               verifun = "EnsRoca")

#to plot ROCA diagram
spatialPlot(lower.tercile,
            backdrop.theme= "countries",
            main = "ROC AREA (Below-normal) for March",
            color.theme = "YlOrRd")

**Comment by rykang11** [comment]
Issue solved by removing member,time axes from the write_netcdf "hyfo" package
